spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogs
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: catalogos-service
  profiles:
    active: dev

server:
  port: 8090